---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: udproutes.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
  scope: Namespaced
  names:
    kind: UDPRoute
    shortNames:
      - ur
    plural: udproutes
    singular: udproute
  versions:
    - name: v1alpha4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - matches
              properties:
                matches:
                  description: Match conditions of this route.
                  type: object
                  required:
                    - ports
                  properties:
                    ports:
                      description: Port numbers to match UDP traffic.
                      type: array
                      items:
                        type: integer
